### ISSUE TITLE
SVGKSourceString.SourceFromContentsOfString returns null

### ISSUE THREAD

**Issue by Bouncaaa** [sushihangover/SVGKit.Binding#1]
I have an SVG file that seems to render fine in a browser. When I take the string data of the SVG file and use the SVGKSourceString.SourceFromContentsOfString method it returns Null in xamarin.iOS.

I have had the same issue trying to create the image from NSData.

Has anybody had this issue?

**Comment by Bouncaaa** [comment]
I forgot to mention I use the nuget version of the binding 1.0.2

**Comment by sushihangover** [comment]
@Bouncaaa It could be a SVGKit issue with that SVG file as I have had SVGs that SVGKit will not parse/render. And in that case you would need to submit an issue at the SVGKit repo.

If it is possible to share the SVG, I'll take a quick look...
