### ISSUE TITLE
'Could not create an native instance of the type' error

### ISSUE THREAD

**Issue by jlord-ifs** [sushihangover/SVGKit.Binding#4]
I'm using the latest version from Nuget and have started getting the following error:

> Could not create an native instance of the type 'SushiHangover.SVGKit.SVGKImage': the native class hasn't been loaded. It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false.

Is there something obvious I'm missing here as nothing else has changed and this library used to work properly?

Thanks in advance.

**Comment by sushihangover** [comment]
Nothing that I know about. What version of `Xamain.iOS` are you  using?

**Comment by jlord-ifs** [comment]
10.8.0.174 (latest I think)

It's odd though, it worked fine on iOS 10.0 or greater and produced that error on iOS 9.0 - 9.3 but now it's also throwing that error on all versions even though I've made no changes to the project.

I'm not using this package in the main Xamarin.iOS project for the app but inside another .iOS project that is self contained and used by the main project. SVGKit is not used beyond that other project and I'm wondering if the issue is that the library is now not being included in the build correctly as it's not used by the main iOS project directly.

**Comment by jlord-ifs** [comment]
I've tested this further and can confirm it works on iOS 10.0, 10.2, 10.3 but fails on any iOS 9 irrelevant of the device type.

**Comment by sushihangover** [comment]
I'll take a look at the SVGKit static library to see if something it in the way it is compiled that would cause a problem on iOS 9. 

Note: I'm not changing anything in the Xcode project or their build script.

**Comment by jlord-ifs** [comment]
@sushihangover Have you been able to replicate this issue on iOS 9?

**Comment by sushihangover** [comment]
@jlord-ifs Totally missed the follow up on this one. 😦 

I'm going to close this for now (I do not have an iOS 9 device anymore). If you still have an issue w/ iOS9 try the native SVGKit project via Xcode on your device. Thanks.
